name: ${pom.name}
main: ${pom.groupId}.${pom.name}
version: ${pom.version}
author: bendem
description: Send messages to other players when you find ores.
website: ${pom.url}

commands:
    ob:
        usage: |
            /<ob> [reload] Reload config from file
        description: OreBroadcast commands
        permission: ob.reload

permissions:
    ob.*:
        description: Give access to all OreBroadcast functionalities
        children:
            ob.reload: true
            ob.broadcast: true
            ob.receive: true
    ob.reload:
        description: Players with this permission can reload the config
        default: op
    ob.broadcast:
        description: Players with this permission will send messages when they find ores.
        default: true
    ob.receive:
        description: Players with this permission will receive OreBroadcast messages.
        default: true
