name: ${pom.name}
main: be.bendem.bukkit.orebroadcast.OreBroadcast
version: ${pom.version}
author: bendem
description: Send messages to other players when you find ores.
website: ${pom.url}

commands:
    ob:
        usage: |
            Commands available:
            /<ob> [reload] Reload config from file
            /<ob> [clear] Clear the content of the block blacklist
        description: OreBroadcast commands
        permission: ob.commands.*

permissions:
    ob.*:
        description: Give access to all OreBroadcast functionalities
        children:
            ob.commands.*: true
            ob.broadcast: true
            ob.receive: true
    ob.commands.*:
        description: Give access to all the plugin commands
        children:
            ob.commands.reload: true
            ob.commands.clear: true
    ob.commands.reload:
        description: Players with this permission can reload the config
        default: op
    ob.commands.clear:
        description: Players with this permission can clear the blacklist
        default: op
    ob.broadcast:
        description: Players with this permission will send messages when they find ores.
        default: true
    ob.receive:
        description: Players with this permission will receive OreBroadcast messages.
        default: true
