name: ${pom.name}
main: ${pom.groupId}.${pom.name}
version: ${pom.version}
author: bendem
description: Broadcast the server when you find ores.

commands:
    ob:
        usage: |
            /<ob> [reload] Reload config from file
        description: OreBroadcast commands
        permission: ob.reload

permissions:
    ob.*:
        description: Give access to all OreBroadcast commands
        children:
            ob.reload: true
            ob.broadcast: true
            ob.receive: true
    ob.reload:
        description: Reload config from file
        default: op
    ob.broadcast:
        description: Broadcast a message when ore is found
        default: true
    ob.receive:
        description: Receive a broadcasted message
        default: true
