ores:
    - coal
    - iron
    - gold
    - lapis
    - redstone
    - quartz
    - diamond
    - emerald
colors:
    coal: dark_gray
    iron: gray
    gold: yellow
    lapis: dark_blue
    redstone: red
    quartz: white
    diamond: aqua
    emerald: green
